version: "3.8"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80" # Single entry point for all traffic
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - "3000" # Only exposed to internal network
    env_file:
      - ./frontend/.env
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost/api # Points to nginx
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "4000" # Only exposed to internal network
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
      - PORT=4000
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

networks:
  app-network:
    driver: bridge
