apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  # MongoDB Connection
  MONGODB_URI: "<your-mongodb-connection-string>"

  # Server Configuration
  PORT: "3001"
  NODE_ENV: "production"

  # Add any other sensitive environment variables here
  # JWT_SECRET: "<your-jwt-secret>"
  # API_KEY: "<your-api-key>"
